In [36]:
import numpy as np

In [37]:
#Homework 1 Problem 1 Part A
# Check the data type of the array
array1=np.random.randint(low=3,high=12,size=(5,7))
array1

array([[ 9, 11,  8,  5,  5,  8, 11],
       [ 4,  5,  5,  7,  3, 10,  7],
       [11,  3,  9,  8, 10,  4,  4],
       [ 4,  3,  9,  8,  7,  7, 10],
       [ 9,  8,  7, 11,  3,  5, 10]])

In [38]:
array1.dtype

dtype('int32')

In [39]:
#Find the maximum Value of the entire array (Part B)
array1.max()

11

In [40]:
#Find the minimum value of each row (Part C)
array1.min(axis=1)

array([5, 3, 3, 3, 3])

In [42]:
#Find the index where the minimum value of each row occurs (Part D)
np.argmin(array1,axis=1)

array([3, 4, 1, 1, 4], dtype=int64)

In [45]:
#Exerxise 2
arr2=np.arange(4,100,5)
arr2

array([ 4,  9, 14, 19, 24, 29, 34, 39, 44, 49, 54, 59, 64, 69, 74, 79, 84,
       89, 94, 99])

In [48]:
#Exercise 3
arr3=arr2.reshape(4,5)
arr3

array([[ 4,  9, 14, 19, 24],
       [29, 34, 39, 44, 49],
       [54, 59, 64, 69, 74],
       [79, 84, 89, 94, 99]])

In [50]:
#Exercise 4
np.random.randn(4,2,3)

array([[[-0.28671918,  1.24936769,  0.57625289],
        [ 2.04447817,  1.13747554,  0.85669457]],

       [[-0.71288518,  0.02384786,  1.51380124],
        [ 0.64149333,  0.78105525,  0.35446381]],

       [[ 0.46343712, -1.20151616,  0.01928307],
        [ 0.24280178,  0.14393731, -1.33766747]],

       [[ 0.75138045,  0.5545406 , -1.28579537],
        [ 0.2267281 ,  1.00526608, -1.00425655]]])

In [59]:
#Exercise 5
arr_eye=np.eye(6,6,k=-2,dtype=int)
arr_eye

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0]])

In [54]:
#Exercise 6
arr4=np.arange(3,35,2)
arr4

array([ 3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33])

In [60]:
#Exercise 6 Part a
arr4[-4:]

array([27, 29, 31, 33])

In [62]:
#Exercise 6 Part b
arr4[arr4%3==0]

array([ 3,  9, 15, 21, 27, 33])

In [65]:
#Exercise 7
arr_2d=np.array([[69, 75, 52, 33,  7, 62, 22],
               [87, 51, 13, 75, 78, 46, 53],
               [43, 24, 58, 76,  3,  3, 57],
               [84, 86, 75, 26, 71, 77,  7],
               [75, 17, 17, 38, 54, 72, 78]])
arr_2d

array([[69, 75, 52, 33,  7, 62, 22],
       [87, 51, 13, 75, 78, 46, 53],
       [43, 24, 58, 76,  3,  3, 57],
       [84, 86, 75, 26, 71, 77,  7],
       [75, 17, 17, 38, 54, 72, 78]])

In [69]:
#Exercise 7 Part A
arr_2d[-1,-2]

72

In [73]:
#Exercise 7 Part B
arr_2d[2:,3:5]

array([[76,  3],
       [26, 71],
       [38, 54]])

In [75]:
arr_2d[1:4,:]

array([[87, 51, 13, 75, 78, 46, 53],
       [43, 24, 58, 76,  3,  3, 57],
       [84, 86, 75, 26, 71, 77,  7]])

In [77]:
#Exercise 8
arr8=np.arange(1,50,3)
arr8

array([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49])

In [80]:
#Exercise 8 part A
arr8[(arr8>7) & (arr8<43)]

array([10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40])

In [81]:
#Exercise 8 part B
arr8[(arr8%2==0) & (arr8>11) & (arr8<45)]

array([16, 22, 28, 34, 40])

In [85]:
#Exercise 9
arr9=np.random.rand(20)
arr9

array([0.85716062, 0.35853023, 0.10733047, 0.46706131, 0.25333663,
       0.24029294, 0.26755984, 0.33381409, 0.7621522 , 0.85650366,
       0.29086039, 0.17741079, 0.84804106, 0.77238059, 0.60407676,
       0.1640956 , 0.95015099, 0.99054729, 0.84716913, 0.99684507])

In [90]:
#Exercise 9 Mean
mean=np.mean(arr9)
mean

0.5572659836048748

In [92]:
#Exercise 9 Standard Deviation
sd=np.std(arr9)
sd

0.30987609836728697

In [94]:
#Exercise 9 Median
median=np.median(arr9)
median

0.5355690361809877

In [98]:
#Exercise 9 Mean of Log values
log=np.log10(arr9)
log

array([-0.06693779, -0.44547422, -0.96927697, -0.33062611, -0.596302  ,
       -0.61925899, -0.57257907, -0.47649533, -0.11795829, -0.06727078,
       -0.53631542, -0.75101997, -0.07158312, -0.11216865, -0.21890787,
       -0.78490307, -0.02220738, -0.00412478, -0.07202988, -0.00137233])

In [99]:
meanlog=np.mean(log)
meanlog

-0.3418406007596105

In [112]:
#Exercise 10 Part A
arr10=np.arange(1,10)
arr10

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [105]:
arr_new=[arr10[-1],arr10[-2],arr10[-3],arr10[-4]]
arr_new

[9, 8, 7, 6]

In [148]:
def reverse(array):
    swag=array[::-1]
    swag=swag.astype('float64')
    print(swag)
    return;

In [149]:
reverse(arr10)

[9. 8. 7. 6. 5. 4. 3. 2. 1.]


In [143]:
#Exercise 10 Part b

array([9, 8, 7, 6, 5, 4, 3, 2, 1])

In [178]:
arr11=np.random.randint(0,11,size=(3,3))
arr11

array([[0, 1, 3],
       [8, 5, 7],
       [3, 9, 1]])

In [157]:
arr11.reshape(1,9)

array([[5, 9, 2, 5, 6, 5, 6, 6, 1]])

In [200]:
def flatten(array):
    numrows = len(array)
    numcols = len(array[0])
    length = numrows*numcols
    flat = array.reshape(1,length)
    print(flat)
    return;

In [201]:
flatten(arr11)

[[0 1 3 8 5 7 3 9 1]]


In [ ]:
#These are some websites I used to get ideas for exercise 10
#https://www.codementor.io/@kaushikpal/user-defined-functions-in-python-8s7wyc8k2
#https://dbader.org/blog/python-reverse-list
#https://www.geeksforgeeks.org/change-data-type-of-given-numpy-array/
#https://stackoverflow.com/questions/10713004/find-length-of-2d-array-python